---
- name: Deploy and Configure EC2 Instance
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Launch EC2 Instance
      ec2_instance:
        instance_type: t2.medium
        image_id: ami-0230bd60aa48260c6
        region: us-east-1
        key_name: ansible
        vpc_subnet_id: subnet-07336005791ff788a
        count: 1
        network:
          assign_public_ip: yes
        wait: yes
        security_group: eshop
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ session_token }}"
      register: ec2_instance_result

    - name: Add instance host to security_group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2_instance_result.instances }}"

    - name: Wait for SSH connection
      delegate_to: "{{ item.public_ip }}"
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: "{{ ec2_instance_result.instances }}"

- name: Configure EC2 Instance
  hosts: launched
  become: true

  tasks:
    - name: Install Git and Docker
      yum:
        name:
          - git
          - docker
        state: latest
        update_cache: true
      become: true

    - service:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Start Docker on startup
      shell: systemctl enable docker
      become: true
    
    - name: Set rights to Docker
      shell: usermod -a -G docker ec2-user
      become: true

    - name: Get eshop from Git
      git:
        repo: 'https://github.com/strbavaclav/4IT572_docker.git'
        dest: ./app
    
    - name: Build Docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: true

    - name: Run Docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 45
      poll: 0
      become: true

    - wait_for:
        port:
          80

